import Head from 'next/head'

import { HeadText } from "../../comps/header";
import {ParaText} from "../../comps/body"
import styled from 'styled-components';
import Router, { useRouter } from 'next/router';
import {ResourceMenu, ResourceBox} from "../../comps/resourcemenu";
import {numberArr, linkArr} from "../../data/resourcedata";
import {useState} from 'react';
import {NavBar} from "../../comps/navbar";
import {LargeButton} from "../../comps/largebutton";
import {SmallButton} from "../../comps/smallbutton";
import { untidyImgs } from '../../data/sampledata';
import { ImgDiv, returnClick } from '../../comps/images';
import { Message } from '../../comps/messagebrowny';
import { message, speech, CleanUp  } from '../../data/activitydata';

const Cont = styled.div`
display: flex;
justify-content: center;
align-items: center;
flex-direction: column;
z-index: auto;
`

export default function Activities() {
  const r = useRouter();
  var { num } = r.query;
  var {shirt} = r.query;
  var {apple} = r.query;
  var {book} = r.query;

  function HandleShirt(){

    StoreAn(qnum, o.num, o.txt, Number(i)),

      r.push({
        pathname: "/quiz/questions",
        query: {
          qnum: Number(qnum),
          click: Number(i)
        }
      }, null, { scroll: false })

  }
 
  
  return (
    <div>
      <Head>
        <title>Cleaning up Activity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/brownyfavicon.svg" />
      </Head>

      <main>
      <NavBar></NavBar>
      </main>

      <Cont>
      <ImgDiv path='/shirt.PNG' 
      size='9em' 
      placement='absolute' 
      zIndex='1' 
      marginLeft='-6em' 
      top='25em'
      onClick={() => 
        r.push({
          pathname: "/activities/cleanup",
          query: {
            num: Number(num) >= 1  ? Number(num) + 1 : Number(num),
            shirt: Number(num) >= 1 ? true : false,
            apple: apple,
            book: book
          }
        }, null, {scroll:false})
      } 
      display = {shirt=== "true" && "none"}
      >
      </ImgDiv>
     
      <ImgDiv 
      path='/apple.PNG' 
      size='6em' 
      placement='absolute' 
      zIndex='1' marginLeft='1em' 
      top='25em'
      className={".test"}
      onClick={() => r.push({
        pathname: "/activities/cleanup",
        query: {
          num: Number(num) >= 1  ? Number(num) + 1 : Number(num),
          apple: Number(num) >= 1 ? true : false,
          shirt: shirt,
          book: book,
        }
      }, null, {scroll:false})
    } 
    display = {apple === "true" && "none"}
    >
        
      </ImgDiv>
     
      <ImgDiv 
      path='/book.PNG' 
      size='9em' 
      placement='absolute' 
      zIndex='1' 
      marginLeft='7em' 
      top='28em'
      onClick={() => r.push({
        pathname: "/activities/cleanup",
        query: {
          num: Number(num) >= 1  ? Number(num) + 1 : Number(num),
          shirt: shirt,
          apple: apple,
          book: Number(num) >= 1 ? true : false,
        }
      }, null, {scroll:false})
    } 
    display = {book=== "true" && "none"}
    >
      </ImgDiv>
      
      <ImgDiv 
      path='/activityRoom.PNG' 
      size='32em'>
      
      </ImgDiv>
      

      {
          Number(num) === 4 &&
          <LargeButton button_text="Take me back" next="/activities"></LargeButton>
        }

      <Message onClick={() => r.push({
        pathname: "/activities/cleanup",
        query: {
          num: Number(num) === 0  ? Number(num) + 1 : Number(num), 
          shirt: shirt,
          apple: apple,
          book: book
        }

      }, null, {scroll:false})} path={speech[num]}></Message>
      
  
      
      </Cont>
    
      
    </div>
  )
}



