import Head from 'next/head'

import { HeadText } from "../../comps/header";
import {ParaText} from "../../comps/body"
import styled from 'styled-components';
import Router, { useRouter } from 'next/router';
import {ResourceMenu, ResourceBox} from "../../comps/resourcemenu";
import {numberArr, linkArr} from "../../data/resourcedata";
import {useState} from 'react';
import {NavBar} from "../../comps/navbar";
import {LargeButton} from "../../comps/largebutton";
import {SmallButton} from "../../comps/smallbutton";
import { untidyImgs } from '../../data/sampledata';
import { ImgDiv, returnClick } from '../../comps/images';
import { Message } from '../../comps/messagebrowny';
import { message, speech, CleanUp  } from '../../data/activitydata';

const Cont = styled.div`
display: flex;
justify-content: center;
align-items: center;
flex-direction: column;
z-index: auto;
`

export default function Activities() {
  const r = useRouter();
  var { num } = r.query;

  if (num === undefined) {
    num = 0;
  }
  
  return (
    <div>
      <Head>
        <title>Activities</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/brownyfavicon.svg" />
      </Head>

      <main>
      <NavBar></NavBar>
      </main>

      <Cont>
      <ImgDiv path='/shirt.png' 
      size='9em' 
      placement='absolute' 
      zIndex='1' 
      marginLeft='-6em' 
      top='25em'
      onClick={() => r.push({
          pathname: "/activities",
          query: {
            num: Number(num) >= 1  ? Number(num) + 1 : Number(num) 
          }
        })
      } 
      >
      </ImgDiv>
     
      <ImgDiv 
      path='/apple.png' 
      size='6em' 
      placement='absolute' 
      zIndex='1' marginLeft='1em' 
      top='25em'
      className={".test"}
      onClick={() => r.push({
        pathname: "/activities",
        query: {
          num: Number(num) >= 1  ? Number(num) + 1 : Number(num) 
        }
      })
    }
      >
        
      </ImgDiv>
     
      <ImgDiv 
      path='/book.png' 
      size='9em' 
      placement='absolute' 
      zIndex='1' 
      marginLeft='7em' 
      top='28em'
      onClick={() => r.push({
        pathname: "/activities",
        query: {
          num: Number(num) >= 1  ? Number(num) + 1 : Number(num) 
        }
      })
    }
      >
      </ImgDiv>
      
      <ImgDiv 
      path='/activityRoom.png' 
      size='32em'>
      </ImgDiv>
      



      <Message onClick={() => r.push({
        pathname: "/activities",
        query: {
          num: Number(num) === 0  ? Number(num) + 1 : Number(num) 
        }

      })} path={speech[num]}></Message>
      
      {
          Number(num) === 4 &&
          <LargeButton button_text="Take me back home"></LargeButton>
        }
      
      </Cont>
    
      
    </div>
  )
}



