import Head from 'next/head'

import { HeadText } from "../../comps/header";
import {ParaText} from "../../comps/body"
import styled from 'styled-components';
import Router, { useRouter } from 'next/router';
import {ResourceMenu, ResourceBox} from "../../comps/resourcemenu";
import {numberArr, linkArr} from "../../data/resourcedata";
import {useState} from 'react';
import {NavBar} from "../../comps/navbar";
import {LargeButton} from "../../comps/largebutton";
import {SmallButton} from "../../comps/smallbutton";
import { untidyImgs } from '../../data/sampledata';
import { ImgDiv, returnClick } from '../../comps/images';
import { Message } from '../../comps/messagebrowny';
import { message, speech, CleanUp  } from '../../data/activitydata';

const Cont = styled.div`
display: flex;
justify-content: center;
align-items: center;
flex-direction: column;
z-index: auto;
`

export default function Activities() {


 
  
  return (
    <div>
      <Head>
        <title>Activities</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/brownyfavicon.svg" />
      </Head>

      <main>
      <NavBar></NavBar>
      </main>

      <Cont>
      <HeadText text="Activities"></HeadText>
      <ImgDiv path='/broom2.gif' size='15em'></ImgDiv>
      <LargeButton button_text="Cleaning your room" next="/activities/cleanup"></LargeButton>
      </Cont>
    
      
    </div>
  )
}



