import Head from 'next/head'

import { HeadText } from "../../comps/header";
import {ParaText} from "../../comps/body"
import styled from 'styled-components';

import {ResourceSlider} from "../../comps/resourceslider"
import {ResourceMenu} from "../../comps/resourcemenu";
import React,{useState} from 'react';
import {NavBar} from "../../comps/navbar";
import { ImgDiv } from '../../comps/images';
import {useRouter} from 'next/router';
import {ImageData} from '../../data/resourceslider'
export default function Resource() {

  const [show,setShow] = useState(true)

  return (
    <div>
      <Head>
        <title>Resources</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/brownyfavicon.svg" />
      </Head>

      <main>
      <NavBar></NavBar>
      </main>
      <ResourceSlider slides={ImageData}></ResourceSlider>


      <ResourceMenu></ResourceMenu>
      
    </div>
  )
}
