import Head from 'next/head'


import { HeadText } from "../comps/header";
import {ParaText} from "../comps/body"

import {ResourceMenu, ResourceBox} from "../comps/resourcemenu";
import {numberArr, linkArr} from "../data/resourcedata";
import {useState} from 'react';
import {NavBar} from "../comps/navbar";
import {LargeButton} from "../comps/largebutton";
import {SmallButton} from "../comps/smallbutton";

export default function Home() {
  return (
    <div>
      <Head>
        <title>MindFull</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/brownyfavicon.svg" />
      </Head>

      <main>
        <HeadText text="Welcome to MindFull" ></HeadText>
        <ParaText text="Mindfull is an app that helps you measure your mental health. "></ParaText>
        <LargeButton button_text="LET'S GET STARTED"></LargeButton>
      </main>
    
      
    </div>
  )
}
