import Head from 'next/head'
import styled from 'styled-components';
import { HeadText } from "../comps/header";
import {ParaText} from "../comps/body"
import {ResourceMenu, ResourceBox} from "../comps/resourcemenu";
import {numberArr, linkArr} from "../data/resourcedata";
import {useState} from 'react';
import {NavBar} from "../comps/navbar";
import {LargeButton} from "../comps/largebutton";
import {SmallButton} from "../comps/smallbutton";
import Router, { useRouter } from "next/router";
import { ImgDiv } from '../comps/images';

const Cont = styled.div`
display: flex;
justify-content: center;
align-items: center;
flex-direction: column;
`

const ParaCont = styled.div`
width:220pt;
margin-top: 10px;
`

const ButtonCont = styled.div`
margin-top:35px;
opacity: 0%;
animation: fadeSide 0.5s ease-in-out forwards;
animation-delay: 1.25s;
`

const FadeDown = styled.div`
animation: fadeDown 0.75s ease-in-out forwards;
`

const FadeUp = styled.div`
animation: fadeUp 0.75s ease-in-out forwards;
`
const ImgCont = styled.div`
width: 100vw;
`
const BackGround = styled.img`
width: 140vw;
position:absolute;
display:flex;
justify-content:center;
opacity: 15%;
overflow: hidden;
margin:0%;
position:fixed;
`


export default function Home() {
  const r = useRouter()
  return (
    <div>
      <ImgCont>
      <BackGround src ="/flowerbg.png"/>
      </ImgCont>
      <Head>
        <title>MindFull</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/brownyfavicon.svg" />
      </Head>

      <Cont>
        <FadeDown>
          <ImgDiv size='18em' marginTop='3em'></ImgDiv>
        </FadeDown>
        <FadeUp>
          <HeadText text="Welcome to MindFull" className={"head"} marginTop='2em' fontSize = '32pt'></HeadText>
          <ParaCont>
            <ParaText 
            text="Mindfull is an app that helps you measure your mental health."
            fontSize = "13pt"
            marginLeft = "20px"
            ></ParaText>
          </ParaCont>
        </FadeUp>
        <ButtonCont>
        <LargeButton button_text="GET STARTED" next="/home"
        ></LargeButton>
        </ButtonCont>
      </Cont>
    
      
    </div>
  )
}
