import Head from 'next/head'

import { HeadText } from "../comps/header";

<Head>
<title>Create Next App</title>
<meta name="description" content="Generated by create next app" />
<link rel="icon" href="/brownyfavicon.svg" />
</Head>


export default function Test(){
    return <HeadText text="Welcome to Mindfull"></HeadText>}


