import Head from 'next/head'

import { HeadText } from "../comps/header";
import {ParaText} from "../comps/body"

import {ResourceMenu, ResourceBox} from "../comps/resourcemenu";
import {numberArr, linkArr} from "../data/resourcedata";
import {useState} from 'react';
import {NavBar} from "../comps/navbar";
import {LargeButton, QueButton} from "../comps/largebutton";
import {SmallButton} from "../comps/smallbutton";
import {Arrow} from "../comps/arrow";
import {MindScale} from "../comps/mindscale";

import {ques} from "../data/questiondata"

import {SpeechBubble} from "../comps/speechbubble";


<Head>
<title>Create Next App</title>
<meta name="description" content="Generated by create next app" />
<link rel="icon" href="/brownyfavicon.svg" />
</Head>


export default function Test(){

    var page = 0

    function StoreAn(qnum,mnum,txt){
      ques[qnum].a = mnum
      ques[2].selected = txt
      console.log(mnum,ques[qnum].a)
      
    }

    const [options, setOptions] = useState()
    
    function toggle(){
      setOptions(true)
    }


    return <div>


          <NavBar></NavBar>


          <HeadText text="Welcome to Mindfull"></HeadText>
          <ParaText></ParaText>


    



            <ResourceMenu></ResourceMenu>
            <LargeButton></LargeButton>
            <SmallButton onClick = {()=>{console.log(ques[2].c[0].txt)}}> </SmallButton>
            
            {ques[2].c.map((o,i)=><QueButton button_text={ques[2].c[i].txt}
            
            onClick = {()=> {StoreAn(i ,ques[2].c[i].num, ques[2].c[i].txt ), console.log(ques[1], ques[2].a)} }
           
           ></QueButton>)}

           

    

      
            <Arrow></Arrow>
            <SpeechBubble></SpeechBubble>
            <MindScale></MindScale>

        

        </div>
}






