import Head from 'next/head'

import { HeadText } from "../../comps/header";
import {ParaText} from "../../comps/body"
import styled from 'styled-components';
import {ResourceMenu, ResourceBox} from "../../comps/resourcemenu";
import {numberArr, linkArr} from "../../data/resourcedata";
import {useState} from 'react';
import {NavBar} from "../../comps/navbar";
import {LargeButton} from "../../comps/largebutton";
import {SmallButton} from "../../comps/smallbutton";
import { ImgDiv } from '../../comps/images';

const Cont = styled.div`
display: flex;
justify-content: center;
align-items: center;
flex-direction: column;
`

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/brownyfavicon.svg" />
      </Head>
      <NavBar></NavBar>
      
      <Cont>
      <ImgDiv path='/browny1.svg' size='20em'></ImgDiv>
      <HeadText text="How are you today?"></HeadText>
      <LargeButton button_text="MEASURE YOUR MINDFULLNESS" next="quiz"></LargeButton>
      <ImgDiv path='/clouds.svg' size='40em'></ImgDiv>
      <ImgDiv path='/leaves.gif' placement='absolute' size='60em' opacity='40%'></ImgDiv>
      </Cont>
    
      
    </div>
  )
}
